/** Approved emails that may create a portal account. Server-only — do not import from client components. */

import { UNAPPROVED_SIGNUP_ERROR } from "./signup-messages.ts";

export { UNAPPROVED_SIGNUP_ERROR };

const APPROVED_SIGNUP_EMAILS = new Set<string>([
  "demo@designmeetup.info",
  "angelinawwu@ucla.edu",
  "amantrip@usc.edu",
  "benxwang7@gmail.com",
  "priya.venki2016@gmail.com",
  "miffy.yq.wang@yale.edu",
  "crj.jeanchen@gmail.com",
  "justinwu137@gmail.com",
  "lcarolyn@stanford.edu",
  "yaritza.designed@gmail.com",
  "waechterez@gmail.com",
  "mudit14.mahajan@gmail.com",
  "tlux10@pratt.edu",
  "amylala228@gmail.com",
  "bymandychen@gmail.com",
  "conch@stanford.edu",
  "dtrao100@gmail.com",
  "tyler.x.song@gmail.com",
  "karenlou@usc.edu",
  "nishatolayiwola@gmail.com",
  "surya@design.inc",
  "tvranjan06@berkeley.edu",
  "alexkim27@gmail.com",
  "damianpizaguirre@gmail.com",
  "designwithjonathan@gmail.com",
  "xuefeiw1031@gmail.com",
  "chloebeckmeyer2203@gmail.com",
  "design@adriancordova.com",
  "hz.helenzhou@gmail.com",
  "fionafang1025@gmail.com",
  "mavis.lohw@gmail.com",
  "xander.deanna@gmail.com",
  "eemily0002@gmail.com",
  "ericwanguxdesign@gmail.com",
  "losaeguavoen@gmail.com",
  "juliagerbino@gmail.com",
  "una@somastacks.com",
  "lin.jessica.design@gmail.com",
  "andreaskruszakin@gmail.com",
  "alextam9@gmail.com",
  "aidenmontesinos15@gmail.com",
  "kdwu@usc.edu",
  "krisha.prabakaran@berkeley.edu",
  "mokcate@gmail.com",
  "yritawang22@gmail.com",
  "lanalabelle04@gmail.com",
  "hhayksargsiann@gmail.com",
  "narayan.ashanahalli@gmail.com",
  "jiadong2024@gmail.com",
  "mingtada@gmail.com",
  "anmisra@alumni.cmu.edu",
  "noellechristinalam08@gmail.com",
  "bdiaz@alumni.stanford.edu",
  "nmrufian@gmail.com",
  "yas@conniezhou.design",
  "emmahilldes@gmail.com",
  "megsarvepalli@gmail.com",
  "logan.douglas103@gmail.com",
  "unasiu8@gmail.com",
  "ookafor410@gmail.com",
  "aaron.chen02@sjsu.edu",
  "dmpatel7@ncsu.edu",
  "felicityl120@g.ucla.edu",
  "sebastianmm.design@gmail.com",
]);

export function isApprovedSignupEmail(email: string) {
  return APPROVED_SIGNUP_EMAILS.has(email.trim().toLowerCase());
}
